### ISSUE TITLE
scéal's Roadmap

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/sceal#1]
This issue contains details & features for upcoming releases of **scéal**.

## Core
- [ ] Website w/ fancy landing page.
- [ ] Authentication (create, login, manage).
- [ ] Story editor based on Markdown (MDX).
- [ ] Public profiles w/ details, following, etc.
- [ ] Like/Dislike/Comments interactions.
- [ ] Social feed based on relevant/follows.
- [ ] User-friendly analytics for writers.

## CI/CD
- [ ] Test/Lint/Format Action: Uses Deno to verify PRs and commits.
- [ ] Devcontainer Config: Builds with Deno pre-installed.
- [ ] Deepsource: Static analysis for improved code quality.
